### ISSUE TITLE
Completed histesh chaudhary course for javascript

### ISSUE THREAD

**Issue by harshilvithlani** [harshilvithlani/LearningJS#1]
https://www.youtube.com/watch?v=vF4b1KFfA3A&list=PLRAV69dS1uWTSu9cVg8jjXW8jndOYYJPP&index=7

**Comment by harshilvithlani** [comment]
1. The first video is about javascript and where it is used,
2. second video in this series is about what tools required for javascript learning
3. Third Video talks about simple hello world code using javascript
4.fourth video teaches the basic use of variables and constants and how it can be used

**Comment by harshilvithlani** [comment]
5.fifth video talks about numbers in javascript
6.in sixth video talks about boolean values in javascript
7.if and else statement are explained in 7th video of the series
8. logical operations are explained in the 8th video.
9. in 9th video var and let keywords are explained in detail

**Comment by harshilvithlani** [comment]
10. in 10th video very complex issues are discussed which every programmer face using javascript
11. in 11th video use of array is taught
12. in 12th video the introduction of function in javascript is explained

**Comment by harshilvithlani** [comment]
13. in this video methods of the array are been explained
14. in this video the default parameters are explained

**Comment by harshilvithlani** [comment]
15th video in this series teaches for loop concept
16th simple todo Trello app using javascript 
17th is a practical assignment on functions
18th video teaches the ForEach Loop in javascript

**Comment by harshilvithlani** [comment]
19th video is the basic introduction and use of objects in javascript
20th video in a series is about the Extended version of Trello app or TrelloV2
21. in this video Methods are taught and "this" Keyword is explained

**Comment by lakhansamani** [comment]
@harshilvithlani a small suggestion, use Grammarly to reduce your grammatically + spelling errors. I see `video` is misspelled in all the comments.

**Comment by harshilvithlani** [comment]
> @harshilvithlani a small suggestion, use Grammarly to reduce your grammatically + spelling errors. I see `video` is misspelled in all the comments.

I will take care 😅😅

**Comment by harshilvithlani** [comment]
22nd Video of the series explains about checking username and password are entered correct or not.
23rd Video of the series explains about generating random numbers. 
24th Video of the series explains about  "==" VS "===" concept.

**Comment by harshilvithlani** [comment]
25th video of the series explains about search from array objects in javascript
26th Video of the series explains about javascript paths.
27th Video of the series explains about Arrow Functions in javascript.
28th Video of the series explains about arrow function and  This keyword in javascript.
29th Video of the series explains about Coercion in javascript.

**Comment by harshilvithlani** [comment]
the 30th video explains the maps and for loop in detail.
 31st video briefs about setting up the web structure of javascript.

**Comment by harshilvithlani** [comment]
In 32nd video of series the concept of changing all texts using javascript is explained 
The 33rd video of the series explains where to keep Js files and selecting elements.

**Comment by harshilvithlani** [comment]
The 34th video of this series explains the form validation and simple application in javascript.
The 35th video of this series explains the Advanced Form validation in javascript.

**Comment by harshilvithlani** [comment]
In the 36th video, a simple ToDo app is developed.
The 37th video of this series ToDo app is Expanded using Html and CSS
The 38th video of this series explains while Loop and Create Text node in JavaScript
The 39th video of this series explains how we can Add Todo with Fade in.
The 40th video of this series explains about classes and objects in JS.
The 41st video of this series explains about CRUD in Local Storage 
The 42nd video of this series explains about passing Json and Stringify
The 43rd video of this series explains Inheritance and Overriding
